version: "2"

linters:
  default: none
  enable:
    - gosec
    - errcheck
    - staticcheck
    - govet
    - revive
    - gocyclo
    - misspell
    - unparam
    - unused
    - prealloc
    - bodyclose
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true